#Rename to config.yaml
network:
  ip: 222.222.222.222
  port: 88 # Forward port on router
  key: "private.key"
  cert: "cert.pem"
credentials:
  password: pass
  username: username
analysis:
  fps: 20 # Camera fps
  seconds: 5 # How many seconds analyze
  faces: 5 # How many faces to send, configurable at runtime
token: 111111111:aaaaaaaaaaaaaaa-1111111111 # Telegram Token
watchDirectory: "." # Files directory (mp4)
users:
  max_tries: 3
  admin: john10 # Telegram username
