version: "3.9"

services:
  yi-hack-control-bot:
    build: .
    image: yi_hack_telegram_bot_image
    container_name: yi_hack_telegram_bot_cont
    network_mode: host
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    volumes:
    - ./running-container:/app
